name: Deploy

on:
   push:
      branches:
         - master
   pull_request:

jobs:
   eslint:
      name: Check eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Cache pnpm modules
           uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-
         - uses: pnpm/action-setup@v2
           with:
              version: 6.29.1
              run_install: true
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
         - run: pnpm check:eslint

   prettier:
      name: Check prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Cache pnpm modules
           uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-
         - uses: pnpm/action-setup@v2
           with:
              version: 6.29.1
              run_install: true
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
         - run: pnpm check:prettier

   typescript:
      name: Check typescript
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Cache pnpm modules
           uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-
         - uses: pnpm/action-setup@v2
           with:
              version: 6.29.1
              run_install: true
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
         - run: pnpm check:typescript

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Cache pnpm modules
           uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-
         - uses: pnpm/action-setup@v2
           with:
              version: 6.29.1
              run_install: true
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
         - run: pnpm test

   build:
      name: Build
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint, unit_tests]
      steps:
         - uses: actions/checkout@v2
         - name: Cache pnpm modules
           uses: actions/cache@v2
           with:
              path: ~/.pnpm-store
              key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                 ${{ runner.os }}-
         - uses: pnpm/action-setup@v2
           with:
              version: 6.29.1
              run_install: true
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
         - run: pnpm build

   deploy_preview:
      name: Deploy (Preview)
      runs-on: ubuntu-latest
      needs: [build]
      if: ${{ github.ref != 'refs/heads/master' && github.event_name == 'pull_request' }}
      steps:
         - uses: actions/checkout@v2
         - uses: amondnet/vercel-action@v20
           with:
              vercel-token: ${{ secrets.VERCEL_TOKEN }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID}}
              vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

   deploy_production:
      name: Deploy (Production)
      runs-on: ubuntu-latest
      needs: [build]
      if: github.ref == 'refs/heads/master'
      steps:
         - uses: actions/checkout@v2
         - uses: amondnet/vercel-action@v20
           with:
              vercel-token: ${{ secrets.VERCEL_TOKEN }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              vercel-args: '--prod'
              vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID}}
              vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
