name: Deploy

on:
   push:
      branches:
         - master
         - feat/github-workflow-ci
   pull_request:

jobs:
   eslint:
      name: Check eslint
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
              cache: yarn
              cache-dependency-path: yarn.lock
         - run: yarn install
         - uses: actions/cache@v2
           with:
              path: .turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-
         - run: yarn check:eslint --cache-dir=.turbo

   prettier:
      name: Check prettier
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
              cache: yarn
              cache-dependency-path: yarn.lock
         - run: yarn install
         - uses: actions/cache@v2
           with:
              path: .turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-
         - run: yarn check:prettier --cache-dir=.turbo

   typescript:
      name: Check typescript
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
              cache: yarn
              cache-dependency-path: yarn.lock
         - run: yarn install
         - uses: actions/cache@v2
           with:
              path: .turbo
              key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
              restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-
         - run: yarn check:typescript --cache-dir=.turbo

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '16.13.0'
              cache: yarn
              cache-dependency-path: yarn.lock
         - run: yarn install
         - run: yarn test --cache-dir=.turbo

   deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: [unit_tests]
      # if: github.ref == 'refs/heads/master'
      if: github.event_name == 'push'
      steps:
         - uses: actions/checkout@v2
         - uses: amondnet/vercel-action@v20
           with:
              vercel-token: ${{ secrets.VERCEL_TOKEN }}
              github-token: ${{ secrets.GITHUB_TOKEN }}
              vercel-args: '--prod'
              vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID}}
              vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
              alias-domains: ${{github.event.head_commit.id}}.insightable.vercel.app
